# Generated by Django 4.1.7 on 2023-04-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patron_email', models.CharField(max_length=256)),
                ('receiver_email', models.CharField(max_length=256)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('converted_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('patron_prev_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True)),
                ('patron_new_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True)),
                ('patron_currency_at_time', models.CharField(max_length=4)),
                ('receiver_prev_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True)),
                ('receiver_new_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True)),
                ('receiver_currency_at_time', models.CharField(max_length=4)),
                ('pending', models.BooleanField()),
                ('accepted', models.BooleanField()),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
